head:
    prefix: certpublish
    label: I18N_OPENXPKI_WF_TYPE_CERTIFICATE_PUBLISHING
    description: I18N_OPENXPKI_WF_TYPE_CERTIFICATE_PUBLISHING_DESC


state:
    INITIAL: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_INITIAL_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_INITIAL_DESC
        action: 
          - initialize > WAITING_FOR_START

    PUBLISH: 
        autorun: 1
        action: 
          - publish_prefix > SUCCESS ? has_prefix
          - publish_profile > SUCCESS ? !has_prefix

    SUCCESS: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_SUCCESS_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_SUCCESS_DESC

    WAITING_FOR_START: 
        autorun: 1
        action: 
          - global_disconnect > PUBLISH ? !run_sync
          - global_noop > PUBLISH ? run_sync


action:
    initialize: 
        class: Workflow::Action::Null
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CERTIFICATE_PUBLISHING_INITIALIZE_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CERTIFICATE_PUBLISHING_INITIALIZE_DESC
        input: 
          - cert_identifier
          - prefix
          - sync
          - publish_key

    publish_prefix: 
        class: OpenXPKI::Server::Workflow::Activity::Tools::PublishCertificate
        input: 
          - cert_identifier
        param: 
            _map_prefix: $prefix
            export_context: 1


    publish_profile: 
        class: OpenXPKI::Server::Workflow::Activity::Tools::PublishCertificate
        input: 
          - cert_identifier
        param:
            export_context: 1
            _map_publish_key: $publish_key

condition:
    has_prefix:
        class: Workflow::Condition::Evaluate
        param:
            test: $context->{prefix};

    run_sync:
        class: Workflow::Condition::Evaluate
        param:
            test: $context->{sync} != 0;

field:
    sync:
        name: sync
        type: server
        required: 0

    prefix:
        name: prefix
        type: server
        required: 0

    publish_key:
        name: publish_key
        type: server
        required: 0

acl:

    CA Operator: 
        creator: any

    RA Operator: 
        creator: any
        fail: 1
        resume: 1
        wakeup: 1
        history: 1
        techlog: 1
        context: 1


    SmartCard:
        creator: self

    System: 
        creator: self

    User: 
        creator: self

