head:
    prefix: metadata
    label: I18N_OPENXPKI_WF_TYPE_CHANGE_METADATA
    description: I18N_OPENXPKI_WF_TYPE_CHANGE_METADATA_DESC

state:
    CHOOSE_ACTION: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_CHOOSE_ACTION_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_CHOOSE_ACTION_DESC
        action: 
          - load_form > DATA_UPDATE
          - terminate > FAILURE
          - persist > SUCCESS

    DATA_UPDATE: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_DATA_UPDATE_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_DATA_UPDATE_DESC
        action: 
          - update_context > CHOOSE_ACTION

    FAILURE: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_FAILURE_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_FAILURE_DESC

    INITIAL: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_INITIAL_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_INITIAL_DESC
        action: 
          - load_data > DATA_UPDATE

    SUCCESS: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_SUCCESS_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_METADATA_SUCCESS_DESC


action:
    load_data: 
        class: OpenXPKI::Server::Workflow::Activity::Tools::LoadCertificateMetadata
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_LOAD_DATA_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_LOAD_DATA_DESC
        input: 
          - cert_identifier
        validator: 
          - global_cert_identifier_exists

    load_form:
        class: OpenXPKI::Server::Workflow::Activity::Noop
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_LOAD_FORM_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_LOAD_FORM_DESC

    persist: 
        class: OpenXPKI::Server::Workflow::Activity::Tools::UpdateCertificateMetadata
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_PERSIST_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_PERSIST_DESC

    terminate: 
        class: OpenXPKI::Server::Workflow::Activity::Noop
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_TERMINATE_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_TERMINATE_DESC

    update_context: 
        class: OpenXPKI::Server::Workflow::Activity::Noop
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_UPDATE_CONTEXT_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_CHANGEMETA_UPDATE_CONTEXT_DESC
        input: 
          - meta_email
          - meta_requestor
          - meta_system_id
        validator: 
          - validate_system_id
          - validate_email


validator:
    validate_system_id: 
        class: OpenXPKI::Server::Workflow::Validator::Connector
        param: 
            error: I18N_OPENXPKI_WORKFLOW_METADATA_WRONG_SYSTEM_ID
            path: metadata.systemid
        arg: 
          - meta_system_id

    validate_email: 
        class: OpenXPKI::Server::Workflow::Validator::Regex
        arg: 
          - $meta_email
          - email


field: 
    meta_email: 
        label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_EMAIL_LABEL
        name: meta_email
        description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_EMAIL_DESC
        placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_EMAIL_PLACEHOLDER
        tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_EMAIL_TOOLTIP
        type: text
        required: 0
        max: 10

    meta_requestor: 
        label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_REQUESTOR_LABEL
        name: meta_requestor
        description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_REQUESTOR_DESC
        placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_REQUESTOR_PLACEHOLDER
        tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_REQUESTOR_TOOLTIP
        type: text
        required: 0

    meta_system_id: 
        label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_SYSTEM_ID_LABEL
        name: meta_system_id
        description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_SYSTEM_ID_DESC
        placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_SYSTEM_ID_PLACEHOLDER
        tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_META_SYSTEM_ID_TOOLTIP
        type: text
        required: 0


acl:
    Anonymous: 
        creator: self

    CA Operator: 
        creator: any

    RA Operator: 
        creator: any

    System: 
        creator: self

    User: 
        creator: self

