head:
    prefix: estenroll
#persister: Volatile

state:
    INITIAL:
        action: initialize parse_request set_profile global_render_subject global_persist_csr set_workflow_attributes > PENDING

    PENDING:
      autorun: 1
      action:
        - global_nice_issue_certificate > SUCCESS

    SUCCESS: ~

action:
    initialize:
        class: OpenXPKI::Server::Workflow::Activity::Noop
        input:
          - server
          - interface
          - endpoint
          - pkcs10
          - transaction_id

    set_profile:
        class: OpenXPKI::Server::Workflow::Activity::Tools::SetContext
        param:
            cert_profile: I18N_OPENXPKI_PROFILE_TLS_SERVER
            cert_subject_style: enroll

    parse_request:
        class: OpenXPKI::Server::Workflow::Activity::Tools::ParsePKCS10
        param:
            req_extensions: certificateTemplate certificateTemplateName challengePassword

    set_workflow_attributes:
         class: OpenXPKI::Server::Workflow::Activity::Tools::SetAttribute
         param:
            _map_cert_subject: "[% IF context.cert_subject %][% context.cert_subject %][% ELSE %][% context.csr_subject %][% END %]"
            _map_transaction_id: $transaction_id


acl:
    System:
        creator: any
        context: 1

    RA Operator:
        creator: any
        fail: 1
        resume: 1
        wakeup: 1
        history: 1
        techlog: 1
        attribute: 1
        context: 1


