# at the moment this is used for display only
label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CERT_SAN_LABEL
name: cert_subject_alt_name
description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CERT_SAN_DESC
#placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CERT_SAN_PLACEHOLDER
#tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CERT_SAN_TOOLTIP
type: cert_subject_alt_name
format: rawlist
template: >
  [% FOREACH san = value %][% san.0 %]:
    [% IF san.0 == 'DNS' %]
      [% USE CheckDNS %][% CheckDNS.valid(san.1, '(I18N_OPENXPKI_UI_DNS_CHECK_FAIL)', '(I18N_OPENXPKI_UI_DNS_CHECK_OK)','(I18N_OPENXPKI_UI_DNS_CHECK_TIMEOUT)','(I18N_OPENXPKI_UI_DNS_CHECK_SKIPPED)') %]
    [% ELSE %][% san.1 %][% END %]
    |
  [% END %]

