# at the moment this is used for display only
label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CERT_SUBJECT_LABEL
name: cert_subject
description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CERT_SUBJECT_DESC
#placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CERT_SUBJECT_PLACEHOLDER
#tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_CERT_SUBJECT_TOOLTIP
type: cert_subject

