label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_COMMENT_LABEL
name: comment
description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_COMMENT_DESC
placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_COMMENT_PLACEHOLDER
tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_COMMENT_TOOLTIP
type: text
required: 0
