name: key_format
label: I18N_OPENXPKI_UI_EXPORT_PRIVATEKEY_KEY_FORMAT_LABEL
description: I18N_OPENXPKI_UI_EXPORT_PRIVATEKEY_KEY_FORMAT_DESC
type: select
required: 1
option:
  item:
    - PKCS12
    - OPENSSL_PRIVKEY
    - PKCS8_PEM
    - PKCS8_DER
    - JAVA_KEYSTORE
  label: I18N_OPENXPKI_UI_EXPORT_PRIVATEKEY_KEY_FORMAT

# for i18n parser
# I18N_OPENXPKI_UI_EXPORT_PRIVATEKEY_KEY_FORMAT_PKCS12
# I18N_OPENXPKI_UI_EXPORT_PRIVATEKEY_KEY_FORMAT_OPENSSL_PRIVKEY
# I18N_OPENXPKI_UI_EXPORT_PRIVATEKEY_KEY_FORMAT_PKCS8_PEM
# I18N_OPENXPKI_UI_EXPORT_PRIVATEKEY_KEY_FORMAT_PKCS8_DER
# I18N_OPENXPKI_UI_EXPORT_PRIVATEKEY_KEY_FORMAT_JAVA_KEYSTORE
