label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_NOTBEFORE_LABEL
name: notbefore
description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_NOTBEFORE_DESC
placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_NOTBEFORE_PLACEHOLDER
tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_NOTBEFORE_TOOLTIP
type: datetime
required: 0
