label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_PASSWORD_LABEL
name: _password
description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_PASSWORD_DESC
placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_PASSWORD_PLACEHOLDER
tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_PASSWORD_TOOLTIP
required: 1
type: passwordverify
