name: revocation_workflow_ids
label: I18N_OPENXPKI_UI_REVOCATION_WORKFLOW_ID
format: rawlist
template: >
  [% IF value %]
  [% USE Workflow; %]
  [% FOREACH wfid = value %]
     [% wfid %] ([% USE Workflow; Workflow.state(wfid) %]) |
  [% END %]
  [% END %]
