label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SIGNER_VALIDITY_OK_LABEL
name: signer_validity_ok
template: "[% IF value %]I18N_OPENXPKI_UI_YES[% ELSIF value == '0' %]failed:I18N_OPENXPKI_UI_NO[% END %]"
format: styled

