label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SIGNER_REVOKED_LABEL
name: signer_revoked
template: "[% IF value %]failed:I18N_OPENXPKI_UI_YES[% ELSIF value == '0' %]I18N_OPENXPKI_UI_NO[% END %]"
format: styled

