# .travis.yml
#
# Note: Travis will run through the 'before_install' and 'install' steps
# before executing 'make test'

language: perl

# Note: language-pack-de is needed for the i18n test
before_install:
#    - sudo apt-get update -qq
    - sudo apt-get install -qq expat libexpat-dev openssl libssl-dev language-pack-de

# Try to get debug from inst stuff
install:
    - cpanm --notest Config::Std Config::Merge Template Proc::SafeExec Module::Install YAML DBD::mysql
#    - "(wget -O Config-Versioned.tar.gz https://github.com/mrscotty/Config-Versioned/tarball/master && tar xzf Config-Versioned.tar.gz)"
## Install Config::Versioned prereqs with --notest before installing Config::Versioned itself
#    - "(cd mrscotty-Config-Versioned-* && cpanm --quiet --installdeps --notest .)"
#    - "(cd mrscotty-Config-Versioned-* && cpanm --quiet .)"
#    - "(wget -O Connector.tar.gz https://github.com/mrscotty/connector/tarball/master && tar xzf Connector.tar.gz)"
#    - "(cd mrscotty-connector-* && cpanm .)"
    - "(cd core/server && cpanm --quiet --installdeps --notest .)"
# The core tests depend on the client library - we install it in a separate perlbrew library space
#    - "perlbrew lib delete oxi-client; perlbrew lib create oxi-client"
#    - "(cd core/server && cpanm --quiet --notest .)"

