Anonymous:
    handler: Anonymous

User:
    handler: User NoAuth

Operator:
    handler: Operator Password

Testing:
    handler: TestAccounts

OTP:
  handler: OneTimePassword

#External Dynamic:
#    handler: External Dynamic Role

#External Static:
#    handler: External Static Role

#Certificate Challenge/Response:
#    handler: Signature

Client Certificate:
    handler: Certificate

_System:
    handler: System

_SmartCard:
    handler: SmartCard

