label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_NOTAFTER_LABEL
name: notafter
description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_NOTAFTER_DESC
placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_NOTAFTER_PLACEHOLDER
tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_NOTAFTER_TOOLTIP
type: datetime
required: 0
