main:
    debug: 0
    type: MySQL
    name: openxpki
    host: localhost
    port: 3306
    user: openxpki
    passwd: openxpki

    # extra options passed to the driver as parameter
    #driver:
    #    LongReadLen: 10000000

    # How often to try to connect to the database on startup if not avail -
    # default is to fail immediately. This is mainly useful if database and
    # OpenXPKI are started by the same init process and the DB might take
    # some time to come up
    #wait_on_init:
    #    retry_count: 10
    #    retry_interval: 30

# To log to a different database create a section "log" by copying and adjusting
# the upper block, e.g.:
#
# log:
#     debug: 0
#     ...

# Set environment values, e.g. locales for Oracle
# this was inside the db section prior v2.2 which does not work as expected
# environment:
#    key: value
