# Shown in the processlist to distinguish multiple instances
name: main

# Location of the log4perl configuration
log4perl: /etc/openxpki/log.conf

# Daemon settings
user:         openxpki
group:        openxpki
socket_file:  /var/openxpki/openxpki.socket
pid_file:     /var/run/openxpkid.pid
stderr:       /var/log/openxpki/stderr.log
tmpdir:       /var/tmp

# This is experimental!
#type: PreFork
prefork:
  min_servers: 5
  min_spare_servers: 5
  max_servers: 25
  max_spare_servers: 10

# environment:
#    key: value

# Session - default is now to use the database to enable node failover
session:
    type: Database
    lifetime: 1200
    # introduced in v2.2: (previous default was hard coded "session")
    table: backend_session

# if you want to keep the session in the filesystem, switch to
# type: File
# directory: /var/openxpki/session

# Which transport to initialize
transport:
    Simple: 1

# Which services to initialize
service:
    Default:
        enabled: 1
        idle_timeout: 120
        # Kill server process if command does not return after n seconds
        # this is still in beta phase, use with caution!
        # max_execution_time: 20

    SCEP:
        enabled: 1

    LibSCEP:
        enabled: 0

# settings for i18n
i18n:
    locale_directory: /usr/share/locale
    default_language: C

