# The content of this file should be written/updated by your own config
# management tools - you can extend the file with your own attributes all
# values are listed on the system status page and are returned via
# "openxpkicli version" call
config: 2.4
package: debian-2.4
commit: 0abcde
