main:
  - key: home
    label: I18N_OPENXPKI_UI_MENU_HOME
    entries: 
      - key:    home!index
        label:  I18N_OPENXPKI_UI_MENU_HOME
      - key:    workflow!mine
        label:  I18N_OPENXPKI_UI_MENU_MY_WORKFLOW
      - key:    certificate!mine
        label:  I18N_OPENXPKI_UI_MENU_MY_CERTIFICATE

  - key:   workflow!index!wf_type!certificate_signing_request_v2
    label: I18N_OPENXPKI_UI_MENU_REQUEST_CERTIFICATE

  - key:   workflow!index!wf_type!certificate_revocation_request_v2
    label: I18N_OPENXPKI_UI_MENU_REVOKE_CERTIFICATE
 
  - key:   info
    label: I18N_OPENXPKI_UI_MENU_INFORMATION
    entries: 
      - key:   information!issuer
        label: I18N_OPENXPKI_UI_MENU_CA_CERTIFICATES
      - key:   crl!index
        label: I18N_OPENXPKI_UI_MENU_CRL

  - key:   certificate!search
    label: I18N_OPENXPKI_UI_MENU_CERTIFICATE_SEARCH
 
