landmark:
  welcome: workflow!index!wf_type!status_system

main:
  - key: home
    label: I18N_OPENXPKI_UI_MENU_HOME
    entries: 
      - key:    workflow!task
        label:  I18N_OPENXPKI_UI_MENU_MY_TASK
      - key:    workflow!mine
        label:  I18N_OPENXPKI_UI_MENU_MY_WORKFLOW
      - key:    certificate!mine
        label:  I18N_OPENXPKI_UI_MENU_MY_CERTIFICATE

  - key: request
    label: I18N_OPENXPKI_UI_MENU_REQUEST
    entries: 
      - key:   workflow!index!wf_type!certificate_signing_request_v2
        label: I18N_OPENXPKI_UI_MENU_REQUEST_CERTIFICATE
      - key:   workflow!index!wf_type!certificate_revocation_request_v2
        label: I18N_OPENXPKI_UI_MENU_REVOKE_CERTIFICATE

  - key:   pkiadm
    label: I18N_OPENXPKI_UI_MENU_PKI_OPERATION
    entries:
      - key:   workflow!index!wf_type!change_metadata
        label: I18N_OPENXPKI_UI_MENU_CHANGE_METADATA
      - key:   workflow!index!wf_type!crl_issuance
        label: I18N_OPENXPKI_UI_MENU_CRL_ISSUE
      - key:   secret!index
        label: I18N_OPENXPKI_UI_MENU_MANAGE_SECRET
      - key:   workflow!start!wf_type!ca_publish
        label: I18N_OPENXPKI_UI_MENU_PUBLISH_CA_CRL


  - key:   info
    label: I18N_OPENXPKI_UI_MENU_INFORMATION
    entries: 
      - key:   information!issuer
        label: I18N_OPENXPKI_UI_MENU_CA_CERTIFICATES
      - key:   crl!index
        label: I18N_OPENXPKI_UI_MENU_CRL
      - key:   workflow!index!wf_type!status_process
        label: I18N_OPENXPKI_UI_MENU_PROCESS_INFORMATION
      - key:   workflow!index!wf_type!status_system
        label: I18N_OPENXPKI_UI_MENU_SYSTEM_STATUS
      - key:   workflow!index!wf_type!report_summary
        label: I18N_OPENXPKI_UI_MENU_REPORT_SUMMARY
      - key:   workflow!index!wf_type!report_full
        label: I18N_OPENXPKI_UI_MENU_REPORT_FULL


  - key:   certificate!search
    label: I18N_OPENXPKI_UI_MENU_CERTIFICATE_SEARCH

  - key:   workflow!search
    label: I18N_OPENXPKI_UI_MENU_WORKFLOW_SEARCH

tasklist:
  - label: I18N_OPENXPKI_UI_TASKLIST_PENDING_REQUEST_LABEL
    description: I18N_OPENXPKI_UI_TASKLIST_PENDING_REQUEST_DESCRIPTION
    query:
      TYPE:
        - certificate_signing_request_v2
      STATE:
        - ONHOLD
        - PENDING
        - PENDING_POLICY_VIOLATION
    cols:
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_SERIAL_LABEL
        field: WORKFLOW_SERIAL
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_UPDATED_LABEL
        field: WORKFLOW_LAST_UPDATE
      - label: I18N_OPENXPKI_UI_WORKFLOW_STATE_LABEL
        field: WORKFLOW_STATE
      - label: I18N_OPENXPKI_UI_CERTIFICATE_SUBJECT
        field: context.cert_subject
      - label: I18N_OPENXPKI_UI_WORKFLOW_CREATOR_LABEL
        template: "[% context.creator %] / [% context.cert_info.requestor_email %]"

  - label: I18N_OPENXPKI_UI_TASKLIST_PENDING_ENROLLMENT_LABEL
    description: I18N_OPENXPKI_UI_TASKLIST_PENDING_ENROLLMENT_DESCRIPTION
    ifempty: hide
    query:
      TYPE:
        - enrollment
      STATE:
        - PENDING_APPROVAL
        - PENDING_MANUAL_AUTHENTICATION
        - PENDING_POLICY
    cols:
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_SERIAL_LABEL
        field: WORKFLOW_SERIAL
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_UPDATED_LABEL
        field: WORKFLOW_LAST_UPDATE
      - label: I18N_OPENXPKI_UI_WORKFLOW_STATE_LABEL
        field: WORKFLOW_STATE
      - label: I18N_OPENXPKI_UI_CERTIFICATE_SUBJECT
        field: context.cert_subject
      - label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SCEP_TID_LABEL
        template: "[% context.scep_tid %]"

  - label: I18N_OPENXPKI_UI_TASKLIST_PENDING_REVOCATION_LABEL
    description: I18N_OPENXPKI_UI_TASKLIST_PENDING_REVOCATION_DESCRIPTION
    ifempty: hide
    query:
      TYPE:
        - certificate_revocation_request_v2
      STATE:
        - PENDING


wfsearch:
   - label: Certificate Subject
     key: cert_subject
     pattern: '*%s*'
     operator: like 

   - label: Requestor
     key: requestor  

   
   - label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SCEP_TID_LABEL
     key: scep_tid 


certsearch:
   - label: Requestor Name
     key: meta_requestor
     pattern: '*%s*'
     operator: like 

   - label: Requestor eMail
     key: meta_email

