landmark:
  welcome: workflow!start!wf_type!status_system

#ping:
#    href: ../cgi-bin/ping.fcgi
#    timeout: 120

main:
  - key: home
    label: I18N_OPENXPKI_UI_MENU_HOME
    entries:
      - key:    workflow!task
        label:  I18N_OPENXPKI_UI_MENU_MY_TASK
      - key:    workflow!mine
        label:  I18N_OPENXPKI_UI_MENU_MY_WORKFLOW
      - key:    certificate!mine
        label:  I18N_OPENXPKI_UI_MENU_MY_CERTIFICATE

  - key: request
    label: I18N_OPENXPKI_UI_MENU_REQUEST
    entries:
      - key:   workflow!index!wf_type!certificate_signing_request_v2
        label: I18N_OPENXPKI_UI_MENU_REQUEST_CERTIFICATE
      - key:   workflow!index!wf_type!certificate_revocation_request_v2
        label: I18N_OPENXPKI_UI_MENU_REVOKE_CERTIFICATE
      - key:   workflow!index!wf_type!certificate_bulk_revoke
        label: I18N_OPENXPKI_UI_MENU_BULK_REVOKE_CERTIFICATE

  - key:   pkiadm
    label: I18N_OPENXPKI_UI_MENU_PKI_OPERATION
    entries:
      - key:   workflow!index!wf_type!change_metadata
        label: I18N_OPENXPKI_UI_MENU_CHANGE_METADATA
      - key:   workflow!index!wf_type!crl_issuance
        label: I18N_OPENXPKI_UI_MENU_CRL_ISSUE
      - key:   secret!index
        label: I18N_OPENXPKI_UI_MENU_MANAGE_SECRET
      - key:   workflow!start!wf_type!ca_publish
        label: I18N_OPENXPKI_UI_MENU_PUBLISH_CA_CRL
      - key:   workflow!index!wf_type!set_motd
        label: I18N_OPENXPKI_UI_MENU_SET_MOTD


  - key:   info
    label: I18N_OPENXPKI_UI_MENU_INFORMATION
    entries:
      - key:   information!issuer
        label: I18N_OPENXPKI_UI_MENU_CA_CERTIFICATES
      - key:   crl!index
        label: I18N_OPENXPKI_UI_MENU_CRL
      - key:   workflow!start!wf_type!status_process
        label: I18N_OPENXPKI_UI_MENU_PROCESS_INFORMATION
      - key:   workflow!start!wf_type!status_system
        label: I18N_OPENXPKI_UI_MENU_SYSTEM_STATUS
      - key:   workflow!index!wf_type!report_summary
        label: I18N_OPENXPKI_UI_MENU_REPORT_SUMMARY
      - key:   workflow!index!wf_type!report_full
        label: I18N_OPENXPKI_UI_MENU_REPORT_FULL


  - key:   certificate!search
    label: I18N_OPENXPKI_UI_MENU_CERTIFICATE_SEARCH

  - key:   workflow!search
    label: I18N_OPENXPKI_UI_MENU_WORKFLOW_SEARCH

  - key:   bulk
    label: I18N_OPENXPKI_UI_MENU_BULK

tasklist:
  - label: I18N_OPENXPKI_UI_TASKLIST_PENDING_REQUEST_LABEL
    description: I18N_OPENXPKI_UI_TASKLIST_PENDING_REQUEST_DESCRIPTION
    query:
      TYPE:
        - certificate_signing_request_v2
      STATE:
        - ONHOLD
        - PENDING
        - PENDING_POLICY_VIOLATION
    cols:
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_SERIAL_LABEL
        field: WORKFLOW_SERIAL
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_UPDATED_LABEL
        field: WORKFLOW_LAST_UPDATE
      - label: I18N_OPENXPKI_UI_WORKFLOW_STATE_LABEL
        field: WORKFLOW_STATE
      - label: I18N_OPENXPKI_UI_CERTIFICATE_SUBJECT
        field: context.cert_subject
      - label: I18N_OPENXPKI_UI_WORKFLOW_CREATOR_LABEL
        template: "[% context.creator %] / [% context.cert_info.requestor_email %]"

  - label: I18N_OPENXPKI_UI_TASKLIST_PENDING_ENROLLMENT_LABEL
    description: I18N_OPENXPKI_UI_TASKLIST_PENDING_ENROLLMENT_DESCRIPTION
    ifempty: hide
    query:
      TYPE:
        - enrollment
      STATE:
        - PENDING_APPROVAL
        - PENDING_MANUAL_AUTHENTICATION
        - PENDING_POLICY
    cols:
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_SERIAL_LABEL
        field: WORKFLOW_SERIAL
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_UPDATED_LABEL
        field: WORKFLOW_LAST_UPDATE
      - label: I18N_OPENXPKI_UI_WORKFLOW_STATE_LABEL
        field: WORKFLOW_STATE
      - label: I18N_OPENXPKI_UI_CERTIFICATE_SUBJECT
        field: context.cert_subject
      - label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_SCEP_TID_LABEL
        template: "[% context.scep_tid %]"

  - label: I18N_OPENXPKI_UI_TASKLIST_PENDING_REVOCATION_LABEL
    description: I18N_OPENXPKI_UI_TASKLIST_PENDING_REVOCATION_DESCRIPTION
    ifempty: hide
    query:
      TYPE:
        - certificate_revocation_request_v2
      STATE:
        - PENDING


bulk:
  - label: I18N_OPENXPKI_UI_BULK_PENDING_REQUEST_LABEL
    description: I18N_OPENXPKI_UI_BULK_PENDING_REQUEST_DESCRIPTION
    attributes:
     - label: I18N_OPENXPKI_UI_SEARCH_CERT_SUBJECT_LABEL
       key: cert_subject
       pattern: '*%s*'
       operator: like

     - label: I18N_OPENXPKI_UI_SEARCH_REQUESTOR_NAME_LABEL
       key: requestor

     - label: I18N_OPENXPKI_UI_SEARCH_SCEP_TID_LABEL
       key: scep_tid

    query:
      TYPE:
        - certificate_signing_request_v2
      STATE:
        - ONHOLD
        - PENDING
        - PENDING_POLICY_VIOLATION

    cols:
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_SERIAL_LABEL
        field: WORKFLOW_SERIAL
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_UPDATED_LABEL
        field: WORKFLOW_LAST_UPDATE
      - label: I18N_OPENXPKI_UI_WORKFLOW_STATE_LABEL
        field: WORKFLOW_STATE
      - label: I18N_OPENXPKI_UI_CERTIFICATE_SUBJECT
        field: context.cert_subject
      - label: I18N_OPENXPKI_UI_WORKFLOW_CREATOR_LABEL
        template: "[% context.creator %] / [% context.cert_info.requestor_email %]"

    buttons:
      -  label: I18N_OPENXPKI_UI_BULK_APPROVE_CSR_LABEL
         action: workflow!bulk!wf_action!csr_approve_csr
         format: expected
         # this is the string used as key
         select: serial
         # this is the name of the object property used as value
         selection: wf_id
      -  label: I18N_OPENXPKI_UI_BULK_REJECT_CSR_LABEL
         format: failure
         action: workflow!bulk!wf_action!csr_reject
         select: serial
         selection: wf_id

  - label: I18N_OPENXPKI_UI_BULK_PENDING_REVOCATION_LABEL
    description: I18N_OPENXPKI_UI_BULK_PENDING_REVOCATION_DESCRIPTION
    attributes:
     - label: I18N_OPENXPKI_UI_SEARCH_CERT_SUBJECT_LABEL
       key: cert_subject
       pattern: '*%s*'
       operator: like

    query:
      TYPE:
        - certificate_revocation_request_v2
      STATE:
        - PENDING

    cols:
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_SERIAL_LABEL
        field: WORKFLOW_SERIAL
      - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_UPDATED_LABEL
        field: WORKFLOW_LAST_UPDATE
      - label: I18N_OPENXPKI_UI_WORKFLOW_STATE_LABEL
        field: WORKFLOW_STATE
      - label: I18N_OPENXPKI_UI_CERTIFICATE_SUBJECT
        template: "[% USE Certificate %][% Certificate.dn(context.cert_identifier,'CN') %]"
      - label: I18N_OPENXPKI_UI_WORKFLOW_CREATOR_LABEL
        field: context.creator

    buttons:
      -  label: I18N_OPENXPKI_UI_BULK_APPROVE_CRR_LABEL
         action: workflow!bulk!wf_action!crr_approve_crr
         format: expected
         # this is the string used as key
         select: serial
         # this is the name of the object property used as value
         selection: wf_id
      -  label: I18N_OPENXPKI_UI_BULK_REJECT_CRR_LABEL
         format: failure
         action: workflow!bulk!wf_action!crr_reject_crr
         select: serial
         selection: wf_id


wfsearch:
    default:
        cols:
          - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_SERIAL_LABEL
            field: WORKFLOW_SERIAL
          - label: I18N_OPENXPKI_UI_WORKFLOW_SEARCH_UPDATED_LABEL
            field: WORKFLOW_LAST_UPDATE
          - label: I18N_OPENXPKI_UI_WORKFLOW_TYPE_LABEL
            field: WORKFLOW_TYPE
          - label: I18N_OPENXPKI_UI_WORKFLOW_STATE_LABEL
            field: WORKFLOW_STATE
          - label: I18N_OPENXPKI_UI_CERTIFICATE_SUBJECT
            template: "[% IF context.cert_subject %][% context.cert_subject %][% ELSIF context.cert_identifier %][% USE Certificate %][% Certificate.body(context.cert_identifier, 'subject') %][% ELSE %]-[% END %]"
          - label: I18N_OPENXPKI_UI_WORKFLOW_CREATOR_LABEL
            template: "[% context.creator %] / [% context.cert_info.requestor_email %]"

        attributes:
          - label: I18N_OPENXPKI_UI_SEARCH_CERT_SUBJECT_LABEL
            key: cert_subject
            pattern: '*%s*'
            operator: like

          - label: I18N_OPENXPKI_UI_SEARCH_REQUESTOR_NAME_LABEL
            key: requestor

          - label: I18N_OPENXPKI_UI_SEARCH_SCEP_TID_LABEL
            key: scep_tid


certsearch:
   - label: I18N_OPENXPKI_UI_SEARCH_REQUESTOR_NAME_LABEL
     key: meta_requestor
     pattern: '*%s*'
     operator: inlike

   - label: I18N_OPENXPKI_UI_SEARCH_REQUESTOR_EMAIL_LABEL
     key: meta_email
     operator: in

   - label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_ENTITY_LABEL
     key: meta_entity
     operator: inlike


certaction:
   - label: I18N_OPENXPKI_UI_DOWNLOAD_PRIVATE_KEY
     workflow: certificate_privkey_export
     condition: keyexport

   - label: I18N_OPENXPKI_UI_CERT_ACTION_RENEW
     workflow: certificate_renewal_request
     condition: issued

   - label: I18N_OPENXPKI_UI_CERT_ACTION_REVOKE
     workflow: certificate_revocation_request_v2
     condition: issued

   - label: I18N_OPENXPKI_UI_CERT_ACTION_UPDATE_METADATA
     workflow: change_metadata
