head: "Certificate Expiry Report, created at: [% export_date %]"
delimiter: "\t"
cutoff_notafter: +000060
include_expired: -000030

cols:
  - head: Requestor eMail
    attribute: meta_email
  - head: Requestor Name
    attribute: meta_requestor
# Note: Adding SANS is very expensive!
#  - head: SANs
#    template: "[% attribute.subject_alt_name.join(', ') %]"
