id: hostname
label: I18N_OPENXPKI_UI_PROFILE_HOSTNAME
description: I18N_OPENXPKI_UI_PROFILE_HOSTNAME_DESC
type: freetext
preset: "[% CN.0.replace(':.*','') %]"
match: \A [a-zA-Z0-9] [a-zA-Z0-9-]* (\.[a-zA-Z0-9-]*[a-zA-Z0-9])* \z
width: 60
placeholder: fully.qualified.example.com
renew: keep

